music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :email, :session_token, uniqueness: true
    validates :password, length:{minimum: 6}, allow_nil: true

    attr_reader :password

    before_validation :ensure_session_token

    def self.find_by_credentials(email, password)
        @user = User.find_by(email: email)
        if @user && @user.is_password?(password)
            return @user
        else
            return nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= generate_session_token
    end

    def generate_session_token
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        token
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
    helper_method :logged_in?, :current_user#, :login(user)
    
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token
    end

    def logout
        current_user.reset_session_token if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login(@user)
            flash[:messages] = ["Login successful, enjoy the tunes."]
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["Invalid username/password"]
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    # def index
    #     User.all
    #     render :index
    # end
    
    def create
        @user = User.new(users_params)
        if @user && @user.save
            login(@user)
            flash[:messages] = ["Account created and login successful"]
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end
    
    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    # def edit
    #     @user = User.find_by_credentials #find_by(id: params[:id])
    #     render :edit
    # end

    # def update
    #     user = User.find_by_credentials
    #     if user.update(users_params)
    #         redirect_to user_url(user)
    #     else
    #         flash.now[:errors] = user.errors.full_messages
    #         render :new
    #     end
    # end

    # def destroy
    #     logout
    #     redirect_to new_session_url
    # end
    
    private
    def users_params
        params.require(:user).permit(:email, :password)
    end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <div class="header">
      <h1>Music App</h1>
    </div>
    <div class="logs">
      <% if logged_in? %>
        <h2>Welcome <%= current_user.email %></h2>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <button>Log Out</button>
          </form>
      <% else %>
        <!--<h2>Log In</h2>-->
          <a href="<% new_session_url %>">Log In</a>
      <% end %>
    </div>
    <%= yield %>
      <br>
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% elsif flash[:messages] %>
        <% flash[:messages].each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <br>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h2>Create Account</h2>
<form action="<%= users_url %>", method="POST">
    <label for="email">Email</label>
    <input id="email" type="text" name="user[email]">
    <label for="password">Password</label>
    <input id="password" type="password" name="user[password]">
    <button>Create</button>
</form>

music_app/app/views/users/show.html.erb
<h2><%= @user.email %></h2>